/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Message.pb-c.h"
void   message__header__init
                     (Message__Header         *message)
{
  static const Message__Header init_value = MESSAGE__HEADER__INIT;
  *message = init_value;
}
size_t message__header__get_packed_size
                     (const Message__Header *message)
{
  assert(message->base.descriptor == &message__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__header__pack
                     (const Message__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__header__pack_to_buffer
                     (const Message__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message__Header *
       message__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message__Header *)
     protobuf_c_message_unpack (&message__header__descriptor,
                                allocator, len, data);
}
void   message__header__free_unpacked
                     (Message__Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message__header__field_descriptors[3] =
{
  {
    "length",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Message__Header, has_length),
    offsetof(Message__Header, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uri_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Message__Header, has_uri_type),
    offsetof(Message__Header, uri_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ret_code",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Message__Header, has_ret_code),
    offsetof(Message__Header, ret_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__header__field_indices_by_name[] = {
  0,   /* field[0] = length */
  2,   /* field[2] = ret_code */
  1,   /* field[1] = uri_type */
};
static const ProtobufCIntRange message__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor message__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "message.Header",
  "Header",
  "Message__Header",
  "message",
  sizeof(Message__Header),
  3,
  message__header__field_descriptors,
  message__header__field_indices_by_name,
  1,  message__header__number_ranges,
  (ProtobufCMessageInit) message__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
