/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Message.proto */

#ifndef PROTOBUF_C_Message_2eproto__INCLUDED
#define PROTOBUF_C_Message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Message__Header Message__Header;


/* --- enums --- */


/* --- messages --- */

struct  _Message__Header
{
  ProtobufCMessage base;
  protobuf_c_boolean has_length;
  uint32_t length;
  protobuf_c_boolean has_uri_type;
  uint32_t uri_type;
  protobuf_c_boolean has_ret_code;
  uint32_t ret_code;
};
#define MESSAGE__HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&message__header__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* Message__Header methods */
void   message__header__init
                     (Message__Header         *message);
size_t message__header__get_packed_size
                     (const Message__Header   *message);
size_t message__header__pack
                     (const Message__Header   *message,
                      uint8_t             *out);
size_t message__header__pack_to_buffer
                     (const Message__Header   *message,
                      ProtobufCBuffer     *buffer);
Message__Header *
       message__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   message__header__free_unpacked
                     (Message__Header *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Message__Header_Closure)
                 (const Message__Header *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor message__header__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Message_2eproto__INCLUDED */
